const recipes = [
  {
    id: 1,
    imageUrl: 'image/white_rice.jpg',
    name: 'Ofada Rice',
    description: 'A delicacy best eating with assorted stew',
    user: 'Sagaciousagacity',
    upvotes: 415,
    downvotes: 29,
    facvourited: 12,
    views: 3,
    review: [],
  },

  {
    id: 2,
    imageUrl: 'image/puff_puff.jpg',
    name: 'Puff Puff',
    description: 'African Puff Puff with flavours',
    user: 'Kelvin',
    upvotes: 214,
    downvotes: 17,
    facvourited: 8,
    views: 34,
    review: [],
  },
  {
    id: 3,
    imageUrl: 'images/garri_epa.jpg',
    name: 'Milked Garri',
    description: 'Chilled, Milked and Sweetened Garri',
    user: 'TheChef',
    upvotes: 90,
    downvotes: 10,
    facvourited: 16,
    views: 13,
    review: [],
  },
  {
    id: 4,
    imageUrl: 'images/porridge.jpg',
    name: 'Yam pottage',
    description: 'Eat this food and forget your sorrow',
    user: 'KitchenRoyal',
    upvotes: 105,
    downvotes: 13,
    facvourited: 19,
    views: 12,
    review: [],
  },
  {
    id: 5,
    imageUrl: 'images/amala_egusi.jpg',
    name: 'Amala with Egusi Soup',
    description: 'Yorubas favourite swallow',
    user: 'KitchenRoyal',
    upvotes: 348,
    downvotes: 8,
    facvourited: 19,
    views: 1,
    review: [],
  },

  {
    id: 6,
    imageUrl: 'images/yam.jpg',
    name: 'Yam with Egg Sauce',
    description: 'One of the best Nigerian delicacy',
    user: 'Sagaciousagacity',
    upvotes: 154,
    downvotes: 3,
    facvourited: 19,
    views: 34,
    review: [],
  },
];

export default recipes;
